version: "3.9"

services:
  wellfound-microblog:
    container_name: wellfound-microblog
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/microblog/app
    ports:
      - "5000:5000"
